name: CI
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
jobs:
  build-launcher:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macOS-m1"]
        jvm: ["https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.3%2B7/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.3_7.tar.gz"]
        include:
          - os: macos-latest
            jvm: "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.3%2B7/OpenJDK17U-jdk_x64_mac_hotspot_17.0.3_7.tar.gz"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: ${{ matrix.jvm }}
      - run: |
          ./mill -i "cs-m1.writeNativeImageScript" generate.sh "" && \
          ./generate.sh && \
          ./mill -i "cs-m1.copyToArtifacts" artifacts/
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: launcher
          path: artifacts/
          if-no-files-found: error
          retention-days: 1
      - name: Test
        run: ./mill -i cs-m1-tests.test
      - run: ./mill -i ci.upload artifacts/
        if: github.event_name == 'push'
        env:
          UPLOAD_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
